const fuel = [
  "Diesel",
  "Eléctrico",
  "Gasolina",
  "GPL",
  "Híbrido (Diesel)",
  "Híbrido (Gasolina)",
  "Hidrogénio",
];

const extras = [
  "Apple CarPlay",
  "Android Auto",
  "Bluetooth",
  "Porta USB",
  "Carregador de smartphone wireless",
  "Sistema de navegação",
  "Head-up display",
  "Acesso Internet",
  "AC automático",
  "AC automático bi-zona",
  "AC automático de 3 zonas",
  "AC automático de 4 ou mais zonas",
  "AC manual",
  "Tecto de abrir/correr eléctrico",
  "Tecto de abrir/correr manual",
  "Tecto de abrir/correr traseiro eléctrico",
  "Tecto panorâmico",
  "Estofos em alcântara",
  "Estofos em meia-pele",
  "Estofos em pele",
  "Estofos em tecido",
  "Banco do condutor com regulação eléctrica",
  "Banco do condutor aquecido",
  "Banco do passageiro aquecido",
  "Bancos dianteiros ventilados",
  "Bancos traseiros ventilados",
  "Apoio de braço dianteiro",
  "Volante desportivo",
  "Volante com patilhas de velocidade",
  "Fecho central sem chave",
  "Arranque sem chave",
  "Desembaciador de pára-brisas",
  "Cruise Control",
  "Cruise Control adaptativo",
  "Cruise Control adaptativo",
  "Faróis Bi-Xenon",
  "Faróis laser",
  "Faróis Xenon",
  "Farol LED",
  "Sensor de estacionamento dianteiro",
  "Sensor de estacionamento traseiro",
  "Assistente de estacionamento",
  "Sistema de estacionamento autónomo",
  "Câmara 360º",
  "Câmara de marcha-atrás",
  "Retrovisores exteriores eletricamente retrateis",
  "Assistente de ângulo morto",
  "Assistente de mudança de faixa",
  "Controlo de proximidade",
  "Condução autónoma básica",
  "Luzes direccionais dinâmicas",
  "Suspensão desportiva",
  "Suspensão pneumática",
];

export default {
  name: "car",
  type: "document",
  title: "Carros",
  fields: [
    {
      name: "name",
      type: "string",
      title: "Título",
      description: "ex: Renault Megane 1.5 DCI 84cv 2020",
      validation: (Rule) => Rule.required(),
    },
    {
      name: "brand",
      type: "reference",
      title: "Marca",
      to: [{ type: "brand" }],
      validation: (Rule) => Rule.required(),
    },
    {
      name: "model",
      type: "string",
      title: "Modelo",
      validation: (Rule) => Rule.required(),
    },
    {
      name: "photos",
      type: "array",
      title: "Fotos",
      of: [{ type: "image" }],
      options: {
        layout: "grid",
      },
      validation: (Rule) => Rule.required(),
    },
    {
      name: "year",
      type: "number",
      title: "Ano",
      validation: (Rule) => Rule.required().min(1900).max(2024),
    },
    {
      name: "price",
      type: "number",
      title: "Preço €",
      validation: (Rule) => Rule.required(),
    },
    {
      name: "km",
      type: "number",
      title: "Quilómetros (km)",
      validation: (Rule) => Rule.required(),
      description: "ex: 90000",
    },
    {
      title: "Caixa",
      name: "transmission",
      type: "string",
      options: {
        list: ["Manual", "Automática"],
      },
      validation: (Rule) => Rule.required(),
    },
    {
      name: "doors",
      type: "number",
      title: "Portas",
      validation: (Rule) => Rule.required().min(1).max(10),
    },
    {
      name: "seats",
      type: "number",
      title: "Lugares",
      validation: (Rule) => Rule.min(1).max(20),
    },
    {
      title: "Combustível",
      name: "fuel",
      type: "string",
      options: {
        list: fuel,
      },
      validation: (Rule) => Rule.required(),
    },
    {
      title: "Extras",
      name: "extras",
      type: "array",
      of: [{ type: "string" }],
      options: {
        list: extras.map((extra) => ({ value: extra, title: extra })),
        layout: "grid",
      },
    },
    {
      title: "Informação extra",
      name: "info",
      type: "text",
      description: "Pequeno texto com mais informação sobre o carro.",
    },
  ],
};
